language: objective-c

cache:
  directories:
    - $HOME/.cocoapods

before_install:
  - gem install cocoapods --no-ri --no-rdoc

before_script:
  - pod setup > /dev/null 2>&1

script:
  - pod lib lint --sources='https://github.com/CocoaPods/Specs'
